Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("Caetano Veloso- Sozinho");
Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("Às vezes no silêncio da noite");
Console.WriteLine("Eu fico imaginando nós dois");
Console.WriteLine("Eu fico ali sonhando acordado");
Console.WriteLine("Juntando o antes, o agora e o depois");
Console.WriteLine("Por que você me deixa tão solto?");
Console.WriteLine("Por que você não cola em mim?");
Console.WriteLine("Tô me sentindo muito sozinho");
Console.WriteLine("Não sou nem quero ser o seu dono");
Console.WriteLine("É que um carinho às vezes cai bem");
Console.WriteLine("Eu tenho os meus desejos e planos secretos");
Console.WriteLine("Só abro pra você, mais ninguém");
Console.WriteLine("Por que você me esquece e some?");
Console.WriteLine("E se eu me interessar por alguém?");
Console.WriteLine("E se ela de repente me ganha?");
Console.WriteLine("Quando a gente gosta");
Console.WriteLine("É claro que a gente cuida");
Console.WriteLine("Fala que me ama");
Console.WriteLine("Só que é da boca pra fora");
Console.WriteLine("Ou você me engana");
Console.WriteLine("Ou não está madura");
Console.WriteLine("Onde está você agora?");
Console.ResetColor();